using System.Linq;

namespace FUEngine.Help;

/// <summary>Temas del manual para la pestaña «Lua — sintaxis y librería» y enlaces desde Spotlight por palabra clave.</summary>
internal static class LuaReferenceDocumentation
{
    public static IReadOnlyList<DocumentationTopic> BuildTopics()
    {
        return new List<DocumentationTopic>
        {
            new(
                id: EngineDocumentation.LuaReferenceIntroTopicId,
                title: "Lua en FUEngine — índice de sintaxis y librería",
                paraQue: "Tener una referencia aparte del manual general: palabras reservadas y funciones típicas conectadas con scripts del motor.",
                porQueImporta: "El mini-IDE y Spotlight enlazan aquí cada palabra clave; así no todas las búsquedas caen en el mismo tema genérico.",
                paragraphs: new[]
                {
                    "Esta pestaña lista solo temas de Lua: las 23 palabras reservadas (Lua 5.5 §3.1, incluye global) y guías sobre tablas, cadenas, errores y bucles que usarás junto a world, self, input y time en onUpdate / hooks.",
                    "En FUEngine los .lua se cargan por el registro del proyecto y se asignan a objetos o capas; no hace falta require() para tu código de juego salvo que el runtime lo exponga explícitamente.",
                    "Usa el cuadro «Buscar en el índice» arriba para filtrar. Desde Spotlight (Ctrl+P), al elegir una palabra clave Lua se abre este panel en el tema concreto.",
                    "Para APIs del motor (world.setTile, self.x, physics.raycast, etc.) abre el manual → «Scripting Lua — referencia completa de APIs»."
                },
                bullets: new[]
                {
                    "Reservadas: and … while (entradas lua-kw-*).",
                    "Guías: pairs, ipairs, pcall, string.format, math.random, etc. (lua-guide-*).",
                    "Mini-IDE: Ctrl+Espacio sugiere APIs; las palabras clave vienen de la misma lista que Spotlight."
                }),

            Kw("and", "Combina dos expresiones booleanas; si la primera es falsa no evalúa la segunda (cortocircuito).",
                "Útil en onUpdate para condiciones compuestas sin llamar a funciones caras si la primera parte ya falla: if input.isKeyDown(Key.W) and self.y > 0 then …",
                "En Lua solo false y nil son falsy; el número 0 es verdadero (a diferencia de otros lenguajes)."),
            Kw("break", "Interrumpe el bucle for / while / repeat más interno y salta a la siguiente instrucción tras el end del bucle.",
                "En bucles que recorren objetos o resultados de raycast, break evita seguir cuando ya encontraste lo que buscabas.",
                "No sale de function; usa return para eso."),
            Kw("do", "Delimita un bloque de ámbito o crea un bloque anónimo do … end para limitar el alcance de variables locales.",
                "Puedes envolver temporales entre do local x = world.findObject(\"x\") end para no dejar nombres sueltos en todo el script.",
                "Útil para acotar el alcance de contadores o flags que solo aplican a un trozo de onUpdate."),
            Kw("else", "Rama alternativa de un if cuando ninguna condición anterior (if / elseif) se cumplió.",
                "Patrón típico: if input.isKeyPressed(Key.Space) then audio.play(\"jump\") else … end.",
                "Puede incluir otro if anidado; elseif suele ser más claro para varias ramas encadenadas."),
            Kw("elseif", "Encadena otra condición sin anidar if; más legible que if dentro de else.",
                "if time.frame < 60 then … elseif time.frame < 120 then … else … end para fases de intro.",
                "Cada elseif lleva su propia condición y then antes del bloque."),
            Kw("end", "Cierra function, if, for, while, repeat y bloques do.",
                "Cada end empareja con la última construcción abierta; el editor resalta pares en el mini-IDE.",
                "Un end de menos o de más produce errores de parseo visibles al guardar o al iniciar Play."),
            Kw("false", "Literal booleano falso (único junto a nil para condiciones negativas en estilo Lua).",
                "Compara con == false solo si guardas booleanos explícitos; muchas APIs devuelven nil cuando no hay resultado.",
                "if not flag then … suele preferirse a == false cuando flag puede ser nil."),
            Kw("for", "Bucle numérico for i = inicio, fin [, paso] do … end o genérico for k, v in iterator do … end.",
                "Numérico: for i = 1, 10 do … — genérico: for id, inst in pairs(lista) do … (ver guía pairs).",
                "En cada frame, for sobre tablas pequeñas está bien; evita tablas enormes sin medir en dispositivos lentos."),
            Kw("function", "Declara función global function nombre() … end, local function anidada, o función anónima function() … end.",
                "Los hooks del motor (function onStart() … end) son funciones globales del chunk que NLua busca por nombre.",
                "local function foo() protege el nombre frente a otros scripts si el entorno lo permite."),
            Kw("global", "Lua 5.5+: declara nombres en ámbito global explícito (global x, y o global *). En 5.4 no es palabra reservada.",
                "En FUEngine prioriza local para estado interno del script; globales compartidas pueden chocar entre scripts.",
                "Útil para depuración rápida; evita global * en código que vaya a producción."),
            Kw("goto", "Salto a una etiqueta ::label:: dentro de la misma función (desde Lua 5.2).",
                "Úsalo con moderación; if/else suele ser más claro. Algunos estilos de equipo lo prohíben.",
                "No cruces límites de bloque que el compilador Lua no permita; respeta el alcance léxico."),
            Kw("if", "Condicional if condición then … [elseif …] [else …] end.",
                "Patrón motor: if input.isKeyDown(Key.E) then game.loadScene(\"Next\") end.",
                "Encadena condiciones costosas al final para aprovechar el cortocircuito de and/or cuando aplique."),
            Kw("in", "Parte del for genérico: for variables in expresión do — la expresión suele ser pairs(t), ipairs(t) o un iterador custom.",
                "Ver guías pairs e ipairs para recorrer tablas devueltas por APIs.",
                "La variable de control del for es local al bucle; no la uses fuera sin copiarla."),
            Kw("local", "Declara variables visibles solo en el bloque actual (archivo, función o do … end).",
                "Recomendado para caches por script: local lastFire = 0 y comparar con time.seconds en onUpdate.",
                "local function declara función local antes de usarla en el mismo bloque (regla de forward declaration en Lua)."),
            Kw("nil", "Ausencia de valor; destruye entrada en tabla si asignas t[k] = nil; es falsy en if.",
                "world.findObject puede devolver nil si no existe; comprueba antes de usar :",
                "Comparar con == nil es explícito; if not x cubre nil y false según lo que quieras expresar."),
            Kw("not", "Negación lógica; not nil y not false son true.",
                "if not self.visible then return end para salir temprano del onUpdate.",
                "not tiene menor precedencia que ==; usa paréntesis si combinas: if not (a == b) then …"),
            Kw("or", "Disyunción con cortocircuito: si la primera expresión es verdadera, no evalúa la segunda.",
                "local name = obj and obj.name or \"sin nombre\" — patrón idiomático con and/or.",
                "Útil para valores por defecto cuando la primera expresión puede ser nil o false."),
            Kw("repeat", "Bucle repeat … until condición — el cuerpo ejecuta al menos una vez.",
                "Menos frecuente que while; útil cuando la condición de salida solo se conoce tras procesar.",
                "Combina con break si necesitas salida anticipada."),
            Kw("return", "Devuelve cero o más valores y sale de la función (o del chunk al cargar).",
                "En callbacks de ui.bind puedes return temprano si el canvas no aplica.",
                "return a, b, c devuelve múltiples valores a quien llamó; muchas APIs del motor ignoran extras."),
            Kw("then", "Palabra clave tras la condición en if condición then.",
                "if time.delta > 0 then self:move(dx, dy) end — delta evita división por cero en lógica por segundo.",
                "elseif y else siguen al mismo if; cada rama necesita su then excepto else."),
            Kw("true", "Literal booleano verdadero.",
                "Flags de componentes o estados propios: local jumping = true.",
                "En condiciones, if jumping then … es idiomático; == true solo si quieres distinguir de otros truthy."),
            Kw("until", "Cierra repeat; la condición es de salida (cuando es true termina el bucle).",
                "repeat … until distancia < 0.1 en pasos de simulación simples.",
                "A diferencia de while, el cuerpo del repeat se ejecuta al menos una vez antes de evaluar until."),
            Kw("while", "Bucle while condición do … end — evalúa la condición antes de cada iteración.",
                "Cuidado con bucles infinitos en onUpdate; normalmente usas if y estado en lugar de while bloqueante largo.",
                "El motor invoca onUpdate cada frame; un while que «espere» tiempo real bloquearía el juego entero."),

            Guide("pairs", "pairs(t) — recorrer tablas como diccionario",
                "Recorrer claves y valores de una tabla asociativa sin orden fijo.",
                "Iterador que devuelve clave, valor para cada entrada de la tabla (orden no garantizado para claves no enteras).",
                "Útil si una API te devuelve una tabla de resultados o guardas datos por id.",
                "for k, v in pairs(unaTablaDevueltaPorApi) do … — el nombre del método depende de la API (p. ej. listas de resultados).",
                "No uses pairs en arrays densos si necesitas orden; usa ipairs o for i = 1, #t."),
            Guide("ipairs", "ipairs(t) — recorrer secuencias array (1..n)",
                "Iterador estándar para arrays con índices 1..n hasta el primer hueco.",
                "Recorre índices enteros desde 1 hasta el primer hueco en la secuencia.",
                "Adecuado para listas ordenadas devueltas por el motor o tablas construidas como arrays.",
                "Si necesitas pares clave/valor arbitrarios, usa pairs en lugar de ipairs."),
            Guide("next", "next(tabla [, clave]) — iteración manual y comprobar si tabla vacía",
                "next(t) devuelve la primera pareja clave, valor; next(t, k) la siguiente.",
                "if next(t) == nil then … comprueba tabla vacía sin contar entradas.",
                "Útil para detectar tablas vacías antes de iterar en lógica de juego.",
                "Relacionado con pairs, que internamente usa el mecanismo de next."),
            Guide("length-operator", "Operador # — longitud de secuencia o cadena",
                "#\"hola\" == 5; para tablas, la longitud de la secuencia consecutiva desde 1.",
                "Tras table.insert al final, #t suele coincidir con el tamaño; tablas con huecos pueden dar resultados sorprendentes.",
                "Para contar entradas de un diccionario arbitrario no uses #; itera o mantén un contador.",
                "Útil con bucles for i = 1, #lista do cuando la lista es un array denso."),
            Guide("tables-construct", "Constructores de tabla { } y campos",
                "local t = { x = 1, y = 2 } o { \"a\", \"b\" } mezcla índices y claves con sintaxis [ ] = .",
                "Agrupa configuración de comportamiento cerca del inicio del script para legibilidad.",
                "Las tablas son el contenedor principal para datos locales y caches entre frames.",
                "Puedes anidar tablas para agrupar estado por enemigo o por sistema (p. ej. cooldowns)."),
            Guide("table-insert-remove", "table.insert / table.remove",
                "insert(t, v) o insert(t, pos, v); remove(t) quita el último de un array, remove(t, 1) el primero.",
                "Para colas simples de eventos en memoria durante un frame.",
                "remove devuelve el elemento quitado; insert desplaza elementos hacia la derecha.",
                "En rutas muy calientes, minimiza insert/remove en el centro del array (coste O(n))."),
            Guide("table-sort-concat", "table.sort y table.concat",
                "sort(t [, comp]) ordena array in-place; concat(t [, sep [, i [, j]]]) une a string.",
                "concat útil para depuración: print(table.concat(debugLines, \"\\n\")).",
                "sort acepta función comparadora comp(a,b) para ordenar por campo o prioridad.",
                "No ordenes tablas enormes cada frame si puedes cachear el resultado."),
            Guide("string-format", "string.format — cadenas con placeholders",
                "string.format(\"vida %d/%d\", hp, maxHp) — similar a printf; %s para strings, %.2f para float.",
                "Prefiere format a concatenar muchas cadenas en bucles ajustados.",
                "En UI con bind puedes formatear números antes de asignar texto al control.",
                "Los especificadores dependen de Lua; revisa manual si necesitas padding o ancho fijo."),
            Guide("string-sub-find", "string.sub, string.find, string.match",
                "sub(s, i, j) extrae por índice; find busca patrón; match con patrones Lua.",
                "Para rutas o ids de asset guardados como string en propiedades de objeto.",
                "find devuelve posiciones inicio/fin si hay coincidencia; útil para parsear tags o prefijos.",
                "Los patrones Lua no son regex POSIX completos; consulta documentación Lua para clases de caracteres."),
            Guide("string-gsub", "string.gsub — sustitución",
                "Sustituye ocurrencias de un patrón en una cadena; devuelve el string nuevo y el número de reemplazos.",
                "Cuidado con patrones complejos en cada frame (coste); cachea resultados si el string no cambia.",
                "Útil para normalizar ids o quitar prefijos de rutas relativas al proyecto.",
                "Puedes usar función de reemplazo como tercer argumento para lógica condicional."),
            Guide("tonumber-tostring", "tonumber y tostring",
                "tonumber(\"42\") → 42; tostring(x) para concatenar números con texto o logs.",
                "Comparar puntuaciones o datos de UI que vienen como string desde bind.",
                "tonumber devuelve nil si el texto no es numérico; comprueba antes de operar.",
                "tostring(nil) == \"nil\" como cadena; no confundas con el valor nil."),
            Guide("type", "type(x) — nombre del tipo Lua",
                "type(1) == \"number\", type(nil) == \"nil\"; útil en depuración defensiva.",
                "if type(fn) == \"function\" then fn() end antes de llamar callbacks opcionales.",
                "Los proxies del motor suelen comportarse como tablas Lua; type puede devolver \"table\".",
                "Combina type con pcall si llamas código que no controlas."),
            Guide("math-common", "math.floor, ceil, max, min, abs, sqrt",
                "floor/ceil para casillas de mundo: local tx = math.floor(self.x).",
                "max/min para clamp: local s = math.max(0, math.min(1, volume)).",
                "abs útil para distancias manhattan aproximadas o diferencias con signo desconocido.",
                "sqrt aparece en distancias; world.findNearestByTag ya optimiza búsquedas sin que calcules todo a mano."),
            Guide("math-random", "math.random — aleatorio (semilla con game.setRandomSeed si aplica)",
                "math.random() en [0,1), math.random(n) en [1,n], math.random(a,b) en rango entero.",
                "En gameplay reproducible fija RuntimeRandomSeed en proyecto o game.setRandomSeed en onStart.",
                "Para loot o spawns usa random tras fijar semilla para depurar comportamiento repetible.",
                "No dependas del orden de llamadas a random entre frames si no controlas la semilla."),
            Guide("pcall-xpcall", "pcall y xpcall — llamar sin tumbar el script",
                "local ok, err = pcall(function() … end) — ok false si error; protege onUpdate si pruebas código nuevo.",
                "Errores no capturados aparecen en consola del editor en Play.",
                "xpcall permite manejador de error para stack o logging personalizado.",
                "Tras un fallo, deja el objeto en estado seguro (p. ej. no avanzar posición)."),
            Guide("error-assert", "error y assert",
                "assert(cond, \"mensaje\") lanza error si cond es false/nil; útil en desarrollo.",
                "Quita asserts costosos en builds finales si medís rendimiento.",
                "error(\"texto\") interrumpe el chunk; úsalo solo para condiciones imposibles.",
                "En código de producción suele preferirse log + return a error() en onUpdate."),
            Guide("select-unpack", "select y ... (argumentos variables)",
                "function foo(...) local n = select(\"#\", …) end — cuenta argumentos.",
                "Algunas APIs del motor pueden pasar argumentos múltiples en callbacks; revisa firma en LuaSpotlightDescriptions.",
                "select(i, …) devuelve el i-ésimo argumento tras la lista variádica.",
                "En Lua 5.1+ table.unpack (o unpack) expande array a lista de retornos; menos usado en scripts cortos de objeto."),
            Guide("comments", "Comentarios -- y --[[ ]]",
                "-- línea; bloque --[[ multilinea ]] para desactivar temporalmente código.",
                "Documenta invariantes (p. ej. \"self.x en casillas mundo\") para quien lea el script después.",
                "Los comentarios no afectan al runtime; úsalos para explicar «por qué», no «qué» obvio.",
                "En revisión de código, un comentario sobre límites de API del motor evita regresiones."),
            Guide("comparison", "Operadores == ~= < > <= >=",
                "~= es distinto; tablas comparan por identidad, no por contenido.",
                "Compara números de posición con tolerancia epsilon si usas física flotante.",
                "== entre strings es por valor; entre tablas solo true si misma referencia.",
                "Combina comparaciones con and/or de forma cortocircuitada para eficiencia."),
            Guide("scope-closures", "Ámbito, closures y upvalues",
                "Una function interna captura variables local del exterior; útil para callbacks de ui.bind que necesitan estado.",
                "Evita capturar referencias pesadas si creas muchos callbacks en bucle.",
                "local en el archivo limita visibilidad al chunk del script cargado por el motor.",
                "Claridad: prefieres pocos upvalues por closure para facilitar hot reload y depuración."),
            Guide("metatable-intro", "Metatablas (intro breve)",
                "__index y __newindex personalizan acceso a campos; avanzado para DSL propios.",
                "La mayoría de scripts de juego en FUEngine no necesitan metatablas; usa tablas simples y APIs del motor.",
                "Los proxies expuestos por NLua pueden tener metatablas ya definidas; no las sobrescribas sin saberlo.",
                "Si necesitas POO ligero, a veces basta una tabla de métodos y dos puntos self:method()."),
            Guide("coroutine-note", "Coroutines (nota)",
                "En FUEngine los scripts corren en el tick del motor; las coroutines Lua no sustituyen onUpdate sin integración explícita del host.",
                "Lua ofrece coroutine.create/wrap; evítalas en scripts de objeto salvo que conozcas el comportamiento exacto de NLua en este motor.",
                "Si necesitas máquinas de estado, variables locales más if/elseif suelen bastar; para temporizadores usa time.seconds, time.delta o contadores en onUpdate.",
                "En scripts de capa (layer) rige el mismo ciclo de vida que en self."),
        };
    }

    private static DocumentationTopic Kw(string word, string paraQue, string p1, string p2) =>
        new(
            id: $"lua-kw-{word}",
            title: $"«{word}» — palabra reservada Lua",
            paraQue: paraQue,
            porQueImporta: "Forma parte del lenguaje; el resaltado del editor y Spotlight la reconocen como palabra clave.",
            paragraphs: new[] { p1, p2 },
            bullets: new[]
            {
                "Tema manual general: «Mini-IDE de scripts» y «Scripting Lua — APIs».",
                "Atajo: Spotlight (Ctrl+P) → escribe el nombre → Enter abre este tema."
            });

    private static DocumentationTopic Guide(string slug, string title, string paraQue, params string[] paragraphs)
    {
        var four = paragraphs.Where(s => !string.IsNullOrWhiteSpace(s)).Take(4).ToList();
        while (four.Count < 4)
            four.Add("Relación con el motor: combina esto con las tablas world, self, input y time descritas en «Scripting Lua — referencia completa de APIs».");
        return new(
            id: $"lua-guide-{slug}",
            title: title,
            paraQue: paraQue,
            porQueImporta: "Patrones habituales junto a las tablas world, self, input y time del runtime FUEngine.",
            paragraphs: four.Take(4).ToArray(),
            bullets: new[]
            {
                "No es palabra reservada; aparece aquí como guía de librería estándar Lua.",
                "Comprueba la versión de Lua embebida del motor si usas APIs muy nuevas."
            });
    }
}
