using System.Linq;

namespace FUEngine.Help;

/// <summary>
/// Temas del manual para la pestaña «Lua — sintaxis y librería» y enlaces desde Spotlight por palabra clave.
/// Misma convención que el manual general: **Para qué**, **Por qué importa**, **En FUEngine** (dónde/cómo en el runtime), **Contenido** con **Dónde**/**Cómo** explícitos cuando aplique, **Puntos clave**, ejemplos en párrafos o remisiones al manual de APIs.
/// </summary>
internal static class LuaReferenceDocumentation
{
    public static IReadOnlyList<DocumentationTopic> BuildTopics()
    {
        return new List<DocumentationTopic>
        {
            new(
                id: EngineDocumentation.LuaReferenceIntroTopicId,
                title: "Lua en FUEngine — índice de sintaxis y librería",
                paraQue: "Tener una referencia aparte del manual general: palabras reservadas, librería estándar y patrones que usarás junto a las APIs del motor.",
                porQueImporta: "El mini-IDE, Spotlight y la pestaña «Lua — sintaxis y librería» comparten el mismo vocabulario; así no mezclas tutoriales genéricos con el comportamiento real de NLua en este ejecutable.",
                paragraphs: new[]
                {
                    "**Dónde:** menú **Ayuda** → pestaña **Lua — sintaxis y librería** (o Spotlight **Ctrl+P** con nombre de guía). **Cómo:** elige un tema en la lista izquierda; la derecha muestra secciones estándar (Para qué, En FUEngine, Contenido…).",
                    "Esta pestaña es la referencia Lua del motor: (1) palabras reservadas (índice lua-kw-*), (2) guías de librería —string, table, math, errores— (lua-guide-*) y (3) temas que cruzan con FUEngine: hooks, carpetas del proyecto, require bajo Scripts/, limitaciones del sandbox.",
                    "Las otras dos pestañas de Ayuda: Manual del motor (editor, mapa, Play, JSON) y Ejemplos de scripts (código listo para copiar). Usa el filtro de la lista o Spotlight (Ctrl+P) para saltar a un tema por nombre.",
                    "En FUEngine cada .lua útil debe estar en scripts.json y asignarse en el Inspector (objeto o capa). Lo habitual es un archivo = un chunk con hooks globales (function onStart … end). Para código compartido entre archivos usa require(\"Modulo\") con el .lua bajo Scripts/ (guía «require, package y módulos»).",
                    "El mini-IDE de la pestaña Scripts valida sintaxis al escribir: si falla la compilación del chunk (p. ej. falta un end), la línea se marca en rojo en el editor además del mensaje en consola al ejecutar. Ctrl+Espacio fuerza autocompletado; el resaltado usa Lua.xshd (LuaFUE).",
                    "Ciclo de vida: al iniciar Play el runtime carga el chunk; los local del nivel superior persisten entre frames hasta hot reload o destruir el contexto. Eso no es guardado en disco: memoria salvo APIs de juego/proyecto.",
                    "Hooks habituales en objetos: onStart, onUpdate(dt), onDestroy; colisiones y triggers según el proyecto. Scripts de capa usan layer.* y onLayerUpdate(dt). Los hooks deben ser funciones globales del chunk con esos nombres.",
                    "Tablas inyectadas (resumen): self, world, input, time, game, audio, physics, ui, ads, … Firmas completas: manual general «Scripting Lua — referencia completa de APIs».",
                    "Sintaxis con dos puntos: self:move(dx, dy) equivale a self.move(self, dx, dy). Fallos «attempt to index a nil value» suelen ser proxy nil o mezcla incorrecta de . y :.",
                    "Errores en Play van a la consola del editor (categoría Lua). pcall / xpcall protegen trozos experimentales en onUpdate. print redirige a la misma consola.",
                    "Rendimiento: evita tablas nuevas cada frame en bucles calientes; pairs sobre mapas enormes tiene coste. Un while largo en un solo frame congela el juego.",
                    "Versión de Lua: intérprete 5.x vía NLua; detalles (bitwise, palabra global, etc.) pueden diferir de tutoriales genéricos. Prioriza este manual y el código fuente (LuaEnvironment, LuaScriptRuntime).",
                    "Sandbox: no hay io ni os ni dofile para acceso libre a disco; require solo carga módulos bajo Scripts/. print y la validación de sintaxis en el editor usan el entorno que expone el motor.",
                    "Filtra por el cuadro de búsqueda de la lista. Spotlight (Ctrl+P) abre palabras clave o temas por id."
                },
                bullets: new[]
                {
                    "Índice: primero reservadas (orden del lenguaje), luego guías de librería, luego temas «motor» (hooks, carpetas, UI).",
                    "APIs completas y flujo Inspector: manual «Scripting Lua — referencia completa de APIs» y «Conectar scripts con el motor»."
                },
                subtitle: "Sintaxis Lua dentro del runtime NLua de FUEngine",
                enMotor: "No es un tutorial de Lua «en cualquier IDE»: aquí el chunk se carga con NLua, sin REPL integrada. world, self, input, time y el resto son los proxies de este runtime; si portas código de Love2D, Roblox o un tutorial genérico, revisa firmas, nil-safety y qué librerías estándar están realmente disponibles en Play."),

            Kw("and", "Combina dos expresiones booleanas; si la primera es falsa no evalúa la segunda (cortocircuito).",
                "Útil en onUpdate para condiciones compuestas sin llamar a funciones caras si la primera parte ya falla: if input.isKeyDown(Key.W) and self.y > 0 then …",
                "En Lua solo false y nil son falsy; el número 0 es verdadero (a diferencia de otros lenguajes).",
                "En FUEngine: encadena condiciones sobre input, self y resultados de world sin asumir tipos de otro motor; el cortocircuito evita llamar a APIs costosas si la primera parte ya falla."),
            Kw("break", "Interrumpe el bucle for / while / repeat más interno y salta a la siguiente instrucción tras el end del bucle.",
                "En bucles que recorren objetos o resultados de raycast, break evita seguir cuando ya encontraste lo que buscabas.",
                "No sale de function; usa return para eso.",
                "En FUEngine: útil al iterar listas devueltas por APIs (p. ej. candidatos de física) sin bloquear el frame entero."),
            Kw("do", "Delimita un bloque de ámbito o crea un bloque anónimo do … end para limitar el alcance de variables locales.",
                "Puedes envolver temporales entre do local x = world.findObject(\"x\") end para no dejar nombres sueltos en todo el script.",
                "Útil para acotar el alcance de contadores o flags que solo aplican a un trozo de onUpdate.",
                "En FUEngine: acota variables locales a un trozo de onUpdate para no contaminar el estado global del chunk entre scripts."),
            Kw("else", "Rama alternativa de un if cuando ninguna condición anterior (if / elseif) se cumplió.",
                "Patrón típico: if input.isKeyPressed(Key.Space) then audio.play(\"jump\") else … end.",
                "Puede incluir otro if anidado; elseif suele ser más claro para varias ramas encadenadas.",
                "En FUEngine: ramas else suelen cubrir «ninguna otra entrada» en lógica de entrada o estados de game; no depende del motor, solo del flujo."),
            Kw("elseif", "Encadena otra condición sin anidar if; más legible que if dentro de else.",
                "if time.frame < 60 then … elseif time.frame < 120 then … else … end para fases de intro.",
                "Cada elseif lleva su propia condición y then antes del bloque.",
                "En FUEngine: encadena fases con time.frame o time.seconds; es el mismo Lua que en otros sitios, pero time.* es la API del motor."),
            Kw("end", "Cierra function, if, for, while, repeat y bloques do.",
                "Cada end empareja con la última construcción abierta; el editor resalta pares en el mini-IDE.",
                "Un end de menos o de más produce errores de parseo visibles al guardar o al iniciar Play.",
                "En FUEngine: un error de end impide que NLua cargue el script; la consola del editor muestra el fallo al iniciar Play."),
            Kw("false", "Literal booleano falso (único junto a nil para condiciones negativas en estilo Lua).",
                "Compara con == false solo si guardas booleanos explícitos; muchas APIs devuelven nil cuando no hay resultado.",
                "if not flag then … suele preferirse a == false cuando flag puede ser nil.",
                "En FUEngine: muchas APIs devuelven nil cuando no hay resultado; false explícito es raro en datos del motor."),
            Kw("for", "Bucle numérico for i = inicio, fin [, paso] do … end o genérico for k, v in iterator do … end.",
                "Numérico: for i = 1, 10 do … — genérico: for id, inst in pairs(lista) do … (ver guía pairs).",
                "En cada frame, for sobre tablas pequeñas está bien; evita tablas enormes sin medir en dispositivos lentos.",
                "En FUEngine: en onUpdate usa for con moderación; el tiempo del frame es acotado y un for muy pesado baja FPS."),
            Kw("function", "Declara función global function nombre() … end, local function anidada, o función anónima function() … end.",
                "Los hooks del motor (function onStart() … end) son funciones globales del chunk que NLua busca por nombre.",
                "local function foo() protege el nombre frente a otros scripts si el entorno lo permite.",
                "En FUEngine: onStart, onUpdate, onDestroy, etc. deben existir como globales para que el runtime los encuentre; no uses el mismo nombre de hook en dos scripts del mismo objeto si el motor no lo permite."),
            Kw("global", "Lua 5.5+: declara nombres en ámbito global explícito (global x, y o global *). En 5.4 no es palabra reservada.",
                "En FUEngine prioriza local para estado interno del script; globales compartidas pueden chocar entre scripts.",
                "Útil para depuración rápida; evita global * en código que vaya a producción.",
                "En FUEngine: el entorno de NLua puede compartirse entre scripts; local reduce colisiones de nombres."),
            Kw("goto", "Salto a una etiqueta ::label:: dentro de la misma función (desde Lua 5.2).",
                "Úsalo con moderación; if/else suele ser más claro. Algunos estilos de equipo lo prohíben.",
                "No cruces límites de bloque que el compilador Lua no permita; respeta el alcance léxico.",
                "En FUEngine: si el compilador Lua del motor lo rechaza, el script no carga; no es un fallo de C#."),
            Kw("if", "Condicional if condición then … [elseif …] [else …] end.",
                "Patrón motor: if input.isKeyDown(Key.E) then game.loadScene(\"Next\") end.",
                "Encadena condiciones costosas al final para aprovechar el cortocircuito de and/or cuando aplique.",
                "En FUEngine: la rama then usa las mismas APIs que en el resto del manual; no hay preprocessor condicional como en C."),
            Kw("in", "Parte del for genérico: for variables in expresión do — la expresión suele ser pairs(t), ipairs(t) o un iterador custom.",
                "Ver guías pairs e ipairs para recorrer tablas devueltas por APIs.",
                "La variable de control del for es local al bucle; no la uses fuera sin copiarla.",
                "En FUEngine: for … in pairs(world.…) depende de qué devuelva cada API; revisa la referencia de APIs."),
            Kw("local", "Declara variables visibles solo en el bloque actual (archivo, función o do … end).",
                "Recomendado para caches por script: local lastFire = 0 y comparar con time.seconds en onUpdate.",
                "local function declara función local antes de usarla en el mismo bloque (regla de forward declaration en Lua).",
                "En FUEngine: local acumula estado por script cargado; no asumas persistencia entre escenas salvo que guardes en datos del proyecto."),
            Kw("nil", "Ausencia de valor; destruye entrada en tabla si asignas t[k] = nil; es falsy en if.",
                "world.findObject puede devolver nil si no existe; comprueba antes de usar :",
                "Comparar con == nil es explícito; if not x cubre nil y false según lo que quieras expresar.",
                "En FUEngine: casi todas las búsquedas (world, física) pueden devolver nil; el patrón if not x then return end es obligatorio."),
            Kw("not", "Negación lógica; not nil y not false son true.",
                "if not self.visible then return end para salir temprano del onUpdate.",
                "not tiene menor precedencia que ==; usa paréntesis si combinas: if not (a == b) then …",
                "En FUEngine: not sobre flags de componentes o visibilidad en self es habitual; no confundas con operadores bitwise (no existen en Lua clásico)."),
            Kw("or", "Disyunción con cortocircuito: si la primera expresión es verdadera, no evalúa la segunda.",
                "local name = obj and obj.name or \"sin nombre\" — patrón idiomático con and/or.",
                "Útil para valores por defecto cuando la primera expresión puede ser nil o false.",
                "En FUEngine: útil con valores por defecto cuando world.findObject o APIs devuelven nil."),
            Kw("repeat", "Bucle repeat … until condición — el cuerpo ejecuta al menos una vez.",
                "Menos frecuente que while; útil cuando la condición de salida solo se conoce tras procesar.",
                "Combina con break si necesitas salida anticipada.",
                "En FUEngine: evita repeat largo en onUpdate; cada iteración consume tiempo del mismo frame."),
            Kw("return", "Devuelve cero o más valores y sale de la función (o del chunk al cargar).",
                "En callbacks de ui.bind puedes return temprano si el canvas no aplica.",
                "return a, b, c devuelve múltiples valores a quien llamó; muchas APIs del motor ignoran extras.",
                "En FUEngine: salir temprano de onUpdate con return reduce trabajo en ese frame; no «pausa» el juego."),
            Kw("then", "Palabra clave tras la condición en if condición then.",
                "if time.delta > 0 then self:move(dx, dy) end — delta evita división por cero en lógica por segundo.",
                "elseif y else siguen al mismo if; cada rama necesita su then excepto else.",
                "En FUEngine: time.delta viene del bucle del motor; no lo sustituyas por un delta inventado."),
            Kw("true", "Literal booleano verdadero.",
                "Flags de componentes o estados propios: local jumping = true.",
                "En condiciones, if jumping then … es idiomático; == true solo si quieres distinguir de otros truthy.",
                "En FUEngine: flags en propiedades @prop o estado local suelen ser booleanos explícitos."),
            Kw("until", "Cierra repeat; la condición es de salida (cuando es true termina el bucle).",
                "repeat … until distancia < 0.1 en pasos de simulación simples.",
                "A diferencia de while, el cuerpo del repeat se ejecuta al menos una vez antes de evaluar until.",
                "En FUEngine: útil al muestrear distancias o estados tras una pasada de lógica."),
            Kw("while", "Bucle while condición do … end — evalúa la condición antes de cada iteración.",
                "Cuidado con bucles infinitos en onUpdate; normalmente usas if y estado en lugar de while bloqueante largo.",
                "El motor invoca onUpdate cada frame; un while que «espere» tiempo real bloquearía el juego entero.",
                "En FUEngine: un while largo en onUpdate congela el frame; usa time.delta y estado entre frames."),

            Guide("pairs", "pairs(t) — recorrer tablas como diccionario",
                "Recorrer claves y valores de una tabla asociativa sin orden fijo.",
                "En FUEngine: úsalo cuando una API devuelve una tabla tipo mapa (p. ej. resultados por id); el orden no está garantizado y no debes depender de él para orden de render o física.",
                "Iterador que devuelve clave, valor para cada entrada de la tabla (orden no garantizado para claves no enteras).",
                "Útil si una API te devuelve una tabla de resultados o guardas datos por id; for k, v in pairs(unaTablaDevueltaPorApi) do … — el nombre del método depende de la API.",
                "No uses pairs en arrays densos si necesitas orden; usa ipairs o for i = 1, #t."),
            Guide("ipairs", "ipairs(t) — recorrer secuencias array (1..n)",
                "Iterador estándar para arrays con índices 1..n hasta el primer hueco.",
                "En FUEngine: útil para listas ordenadas que devuelve el motor (cuando la documentación de la API dice que es un array 1..n).",
                "Recorre índices enteros desde 1 hasta el primer hueco en la secuencia.",
                "Adecuado para listas ordenadas devueltas por el motor o tablas construidas como arrays; si necesitas pares clave/valor arbitrarios, usa pairs."),
            Guide("next", "next(tabla [, clave]) — iteración manual y comprobar si tabla vacía",
                "next(t) devuelve la primera pareja clave, valor; next(t, k) la siguiente.",
                "En FUEngine: if next(t) == nil then … comprueba tabla vacía antes de lógica; mismas tablas que rellenan las APIs del motor.",
                "if next(t) == nil then … comprueba tabla vacía sin contar entradas; útil antes de iterar en lógica de juego.",
                "Relacionado con pairs, que internamente usa el mecanismo de next."),
            Guide("length-operator", "Operador # — longitud de secuencia o cadena",
                "#\"hola\" == 5; para tablas, la longitud de la secuencia consecutiva desde 1.",
                "En FUEngine: # sirve para arrays densos; tablas devueltas por APIs con huecos pueden dar resultados sorprendentes.",
                "Tras table.insert al final, #t suele coincidir con el tamaño; tablas con huecos pueden dar resultados sorprendentes.",
                "Para contar entradas de un diccionario arbitrario no uses #; itera o mantén un contador.",
                "Útil con bucles for i = 1, #lista do cuando la lista es un array denso."),
            Guide("tables-construct", "Constructores de tabla { } y campos",
                "local t = { x = 1, y = 2 } o { \"a\", \"b\" } mezcla índices y claves con sintaxis [ ] = .",
                "En FUEngine: agrupa configuración de gameplay (velocidades, cooldowns) en tablas locales; no se serializan solas al proyecto.",
                "Agrupa configuración de comportamiento cerca del inicio del script para legibilidad.",
                "Las tablas son el contenedor principal para datos locales y caches entre frames.",
                "Puedes anidar tablas para agrupar estado por enemigo o por sistema (p. ej. cooldowns)."),
            Guide("table-insert-remove", "table.insert / table.remove",
                "insert(t, v) o insert(t, pos, v); remove(t) quita el último de un array, remove(t, 1) el primero.",
                "En FUEngine: útil para colas de eventos en memoria durante un frame; no persisten en JSON salvo que tú guardes.",
                "remove devuelve el elemento quitado; insert desplaza elementos hacia la derecha.",
                "En rutas muy calientes, minimiza insert/remove en el centro del array (coste O(n))."),
            Guide("table-sort-concat", "table.sort y table.concat",
                "sort(t [, comp]) ordena array in-place; concat(t [, sep [, i [, j]]]) une a string.",
                "En FUEngine: concat útil para logs en consola del editor; sort no ordena mapas arbitrarios sin claves numéricas.",
                "concat útil para depuración: print(table.concat(debugLines, \"\\n\")).",
                "sort acepta función comparadora comp(a,b) para ordenar por campo o prioridad.",
                "No ordenes tablas enormes cada frame si puedes cachear el resultado."),
            Guide("string-format", "string.format — cadenas con placeholders",
                "string.format(\"vida %d/%d\", hp, maxHp) — similar a printf; %s para strings, %.2f para float.",
                "En FUEngine: formatea texto antes de asignarlo a UI con bind o para mensajes en consola; el motor no traduce cadenas automáticamente.",
                "Prefiere format a concatenar muchas cadenas en bucles ajustados.",
                "En UI con bind puedes formatear números antes de asignar texto al control.",
                "Los especificadores dependen de Lua; revisa manual si necesitas padding o ancho fijo."),
            Guide("string-sub-find", "string.sub, string.find, string.match",
                "sub(s, i, j) extrae por índice; find busca patrón; match con patrones Lua.",
                "En FUEngine: parsea rutas de assets o ids guardados en propiedades de objeto; rutas son relativas al proyecto.",
                "Para rutas o ids de asset guardados como string en propiedades de objeto.",
                "find devuelve posiciones inicio/fin si hay coincidencia; útil para parsear tags o prefijos.",
                "Los patrones Lua no son regex POSIX completos; consulta documentación Lua para clases de caracteres."),
            Guide("string-gsub", "string.gsub — sustitución",
                "Sustituye ocurrencias de un patrón en una cadena; devuelve el string nuevo y el número de reemplazos.",
                "En FUEngine: normaliza rutas o IDs antes de pasarlos a world o audio; evita gsub pesado cada frame.",
                "Cuidado con patrones complejos en cada frame (coste); cachea resultados si el string no cambia.",
                "Útil para normalizar ids o quitar prefijos de rutas relativas al proyecto.",
                "Puedes usar función de reemplazo como tercer argumento para lógica condicional."),
            Guide("tonumber-tostring", "tonumber y tostring",
                "tonumber(\"42\") → 42; tostring(x) para concatenar números con texto o logs.",
                "En FUEngine: útil al leer @prop numéricas como string o al mostrar valores en UI/debug.",
                "Comparar puntuaciones o datos de UI que vienen como string desde bind.",
                "tonumber devuelve nil si el texto no es numérico; comprueba antes de operar.",
                "tostring(nil) == \"nil\" como cadena; no confundas con el valor nil."),
            Guide("type", "type(x) — nombre del tipo Lua",
                "type(1) == \"number\", type(nil) == \"nil\"; útil en depuración defensiva.",
                "En FUEngine: útil antes de llamar callbacks o al inspeccionar valores devueltos por proxies; muchos son «table».",
                "if type(fn) == \"function\" then fn() end antes de llamar callbacks opcionales.",
                "Los proxies del motor suelen comportarse como tablas Lua; type puede devolver \"table\".",
                "Combina type con pcall si llamas código que no controlas."),
            Guide("math-common", "math.floor, ceil, max, min, abs, sqrt",
                "floor/ceil para casillas de mundo: local tx = math.floor(self.x).",
                "En FUEngine: combina con tamaño de tile del proyecto (ProjectInfo.TileSize) para lógica a grid.",
                "max/min para clamp: local s = math.max(0, math.min(1, volume)).",
                "abs útil para distancias manhattan aproximadas o diferencias con signo desconocido.",
                "sqrt aparece en distancias; world.findNearestByTag ya optimiza búsquedas sin que calcules todo a mano."),
            Guide("math-random", "math.random — aleatorio (semilla con game.setRandomSeed si aplica)",
                "math.random() en [0,1), math.random(n) en [1,n], math.random(a,b) en rango entero.",
                "En FUEngine: fija RuntimeRandomSeed en proyecto o game.setRandomSeed en onStart para reproducir builds; el RNG es el del motor.",
                "En gameplay reproducible fija RuntimeRandomSeed en proyecto o game.setRandomSeed en onStart.",
                "Para loot o spawns usa random tras fijar semilla para depurar comportamiento repetible.",
                "No dependas del orden de llamadas a random entre frames si no controlas la semilla."),
            Guide("pcall-xpcall", "pcall y xpcall — llamar sin tumbar el script",
                "local ok, err = pcall(function() … end) — ok false si error; protege onUpdate si pruebas código nuevo.",
                "En FUEngine: un error no capturado en onUpdate puede cortar el script; pcall mantiene el juego vivo y el error en consola.",
                "Errores no capturados aparecen en consola del editor en Play.",
                "xpcall permite manejador de error para stack o logging personalizado.",
                "Tras un fallo, deja el objeto en estado seguro (p. ej. no avanzar posición)."),
            Guide("error-assert", "error y assert",
                "assert(cond, \"mensaje\") lanza error si cond es false/nil; útil en desarrollo.",
                "En FUEngine: útil en desarrollo; en onUpdate de producción suele preferirse log + return para no tumbar el frame.",
                "Quita asserts costosos en builds finales si medís rendimiento.",
                "error(\"texto\") interrumpe el chunk; úsalo solo para condiciones imposibles.",
                "En código de producción suele preferirse log + return a error() en onUpdate."),
            Guide("select-unpack", "select y ... (argumentos variables)",
                "function foo(...) local n = select(\"#\", …) end — cuenta argumentos.",
                "En FUEngine: algunos callbacks de UI o APIs pueden pasar varios argumentos; revisa la firma en la referencia de APIs.",
                "Algunas APIs del motor pueden pasar argumentos múltiples en callbacks; revisa firma en LuaSpotlightDescriptions.",
                "select(i, …) devuelve el i-ésimo argumento tras la lista variádica.",
                "En Lua 5.1+ table.unpack (o unpack) expande array a lista de retornos; menos usado en scripts cortos de objeto."),
            Guide("comments", "Comentarios -- y --[[ ]]",
                "-- línea; bloque --[[ multilinea ]] para desactivar temporalmente código.",
                "En FUEngine: documenta unidades (world vs tile) y qué APIs pueden devolver nil; ayuda en hot reload y revisión.",
                "Documenta invariantes (p. ej. \"self.x en casillas mundo\") para quien lea el script después.",
                "Los comentarios no afectan al runtime; úsalos para explicar «por qué», no «qué» obvio.",
                "En revisión de código, un comentario sobre límites de API del motor evita regresiones."),
            Guide("comparison", "Operadores == ~= < > <= >=",
                "~= es distinto; tablas comparan por identidad, no por contenido.",
                "En FUEngine: compara posiciones con tolerancia si usas física flotante; no compares proxies de objetos con == salvo misma referencia.",
                "Compara números de posición con tolerancia epsilon si usas física flotante.",
                "== entre strings es por valor; entre tablas solo true si misma referencia.",
                "Combina comparaciones con and/or de forma cortocircuitada para eficiencia."),
            Guide("scope-closures", "Ámbito, closures y upvalues",
                "Una function interna captura variables local del exterior; útil para callbacks de ui.bind que necesitan estado.",
                "En FUEngine: útil al registrar callbacks de UI; evita capturar referencias pesadas si creas muchos en un bucle por frame.",
                "Evita capturar referencias pesadas si creas muchos callbacks en bucle.",
                "local en el archivo limita visibilidad al chunk del script cargado por el motor.",
                "Claridad: prefieres pocos upvalues por closure para facilitar hot reload y depuración."),
            Guide("metatable-intro", "Metatablas (intro breve)",
                "__index y __newindex personalizan acceso a campos; avanzado para DSL propios.",
                "En FUEngine: la mayoría de juegos no necesitan metatablas; usa tablas simples y APIs del motor. Los proxies NLua pueden tener metatablas ya definidas.",
                "La mayoría de scripts de juego en FUEngine no necesitan metatablas; usa tablas simples y APIs del motor.",
                "Los proxies expuestos por NLua pueden tener metatablas ya definidas; no las sobrescribas sin saberlo.",
                "Si necesitas POO ligero, a veces basta una tabla de métodos y dos puntos self:method()."),
            Guide("coroutine-note", "Coroutines (nota)",
                "En FUEngine los scripts corren en el tick del motor; las coroutines Lua no sustituyen onUpdate sin integración explícita del host.",
                "En FUEngine: evita coroutine.create/wrap en scripts de objeto salvo que conozcas NLua aquí; usa time + estado en onUpdate.",
                "Lua ofrece coroutine.create/wrap; evítalas en scripts de objeto salvo que conozcas el comportamiento exacto de NLua en este motor.",
                "Si necesitas máquinas de estado, variables locales más if/elseif suelen bastar; para temporizadores usa time.seconds, time.delta o contadores en onUpdate.",
                "En scripts de capa (layer) rige el mismo ciclo de vida que en self."),
            Guide("colon-syntax", "Dos puntos (:) — métodos con self implícito",
                "obj:foo(a, b) es azúcar sintáctico para obj.foo(obj, a, b). Úsalo con APIs del motor que esperan el objeto como primer parámetro (p. ej. self:move(dx, dy)).",
                "En FUEngine: world:instantiate(...) y self:move(...) dependen de cómo el binding expone la tabla; si falla, prueba la forma con punto y self explícito.",
                "world:instantiate(\"seed\", x, y) encaja cuando la API está enlazada como método de la tabla world; si falla, prueba world.instantiate(world, ...) según versión del binding.",
                "No mezcles : y . al azar: self.move(dx, dy) puede fallar si move exige self como primer argumento.",
                "En el mini-IDE, las sugerencias tras self. listan miembros; las que son «métodos» suelen llamarse con : desde una variable proxy."),
            Guide("print-debug", "print y depuración rápida",
                "print(\"x=\", self.x, \"y=\", self.y) muestra varios valores en la consola del editor durante Play.",
                "En FUEngine: la salida va a la consola del editor (categoría Lua); no es un archivo de log automático salvo que configures otro sistema.",
                "Para tablas grandes, imprime solo claves relevantes o usa string.format para una línea legible.",
                "Los mensajes suelen etiquetarse como Lua en el filtro de la consola; sube el nivel de detalle si no ves nada.",
                "Sustituye prints densos en bucles por contadores (cada N frames) para no inundar el log."),
            Guide("nil-safe-patterns", "Patrones nil-safe (and, or, early return)",
                "local target = world.findObject(\"Enemy\") — if not target then return end evita errores al usar target.x en el mismo frame.",
                "En FUEngine: world y física devuelven nil con frecuencia; este patrón es obligatorio antes de usar self: o campos.",
                "local dist = (target and target.x) and math.abs(self.x - target.x) — encadena comprobaciones antes de operar.",
                "La API puede devolver nil si no hay resultado; documenta en comentarios qué funciones garantizan objeto.",
                "Combina con pcall si llamas código dinámico (p. ej. invoke de componente) y no controlas errores internos."),

            Guide("string-misc", "string.upper, lower, rep, reverse, byte, char",
                "Funciones auxiliares para normalizar texto, repetir caracteres y convertir entre bytes y caracteres.",
                "En FUEngine: útil al comparar ids de tags, rutas de assets en minúsculas o al preparar texto para UI; evita upper/lower en cada frame sobre cadenas largas sin caché.",
                "string.upper(s) / string.lower(s) devuelven copia nueva; string.rep(s, n) repite; string.reverse invierte.",
                "string.byte(s [, i [, j]]) devuelve códigos numéricos; string.char(...) reconstruye cadena desde códigos.",
                "Para patrones complejos sigue usando string.find/match/gsub; byte/char es útil para protocolos ASCII o caracteres concretos."),

            Guide("table-pack-unpack", "table.pack y unpack / table.unpack",
                "Empaqueta argumentos en una tabla con campo n (Lua 5.2+); unpack expande una secuencia a valores múltiples.",
                "En FUEngine: útil al envolver callbacks o al pasar listas a APIs que esperan varios retornos; en el sandbox de juego comprueba que unpack exista como global o como table.unpack.",
                "local t = table.pack(a, b, c) — t.n es el número de argumentos.",
                "table.unpack(t [, i [, j]]) o unpack(t) en Lua 5.1 devuelve valores sueltos; combina con pcall para llamadas variádicas.",
                "No confundas con múltiples retornos de APIs del motor: revisa la firma en la referencia de APIs."),

            Guide("math-trig", "math.sin, cos, tan, atan, atan2, rad, deg, pi",
                "Trigonometría en radianes; math.deg y math.rad convierten; math.pi es constante.",
                "En FUEngine: útil para movimiento circular, rotaciones de sprites o ángulos hacia el jugador; el motor usa coordenadas de mundo según tu lógica (no hay «norte» mágico salvo que lo definas).",
                "atan2(y, x) devuelve ángulo respecto al eje X; evita división por cero de atan(y/x).",
                "Combina con math.sqrt para distancias euclídeas cuando no baste world.findNearestByTag u otras APIs.",
                "Cuidado con coste: trig pesada en miles de objetos por frame; cachea ángulos cuando el objetivo no cambia."),

            Guide("math-pow-log", "math.pow, sqrt, log, exp, floor",
                "Potencias, raíz cuadrada, logaritmos y exponencial; math.floor para discretizar.",
                "En FUEngine: útil para curvas de dificultad, daño escalado, o pasar de espacio lineal a logarítmico en UI.",
                "math.pow(x,y) o x^y en Lua 5.x; math.log(x [, base]) por defecto natural.",
                "math.exp(x) es e^x; combina con math.min/max para clamp.",
                "Para casillas de grid usa floor/ceil en lugar de truncar con casts de otros lenguajes."),

            Guide("os-clock-time", "os.clock, os.time, os.date — tiempo y reloj",
                "os.clock() devuelve tiempo aproximado de CPU usado por el proceso; os.time y os.date trabajan con fechas calendario.",
                "En FUEngine: útil para medir microbenchmarks de un trozo de Lua; para tiempo de juego usa time.seconds / time.delta del motor, no asumas que os.time refleja el «tiempo de partida».",
                "os.date(\"*t\", t) devuelve tabla con año, mes, día, hora; os.time(tabla) convierte a timestamp.",
                "En algunos entornos embebidos parte de os puede estar limitada; si una llamada falla, usa solo APIs del motor.",
                "No uses os.clock para lógica de gameplay online sin sincronizar servidor; aquí es single-player local salvo que añadas red."),

            Guide("require-package", "require, package y módulos en FUEngine",
                "En Lua estándar, require() carga módulos y los cachea en package.loaded.",
                "En FUEngine (Play) el runtime inyecta require y package.loaded en el entorno de cada script. Solo cargan archivos bajo Scripts/ del proyecto (p. ej. require(\"MiLib\") → Scripts/MiLib.lua). No hay acceso a rutas fuera del proyecto ni .. en el nombre del módulo.",
                "El chunk del módulo se ejecuta con el mismo entorno que el script principal (self, world, …). El archivo debe devolver una tabla (o true si no hay return).",
                "Tras hot reload de un script se vacía la caché de módulos; los require se vuelven a cargar en la siguiente ejecución.",
                "Librerías de terceros que dependan de io, os o debug en crudo suelen requerir adaptación al sandbox."),

            Guide("io-debug-note", "io.* y debug.* en el entorno embebido",
                "La librería io ofrece ficheros, y debug introspección de la VM; en juegos embebidas suelen estar limitadas.",
                "En FUEngine: no asumas io.open disponible en Play del jugador final; la escritura de disco puede estar deshabilitada o ser peligrosa.",
                "debug.traceback, debug.getinfo pueden existir para depuración; quítalos o protégelos en builds finales.",
                "Para logs usa print y la consola del editor (Play) o sistemas de juego que el motor exponga.",
                "Si necesitas persistencia, usa APIs de proyecto/juego documentadas, no ficheros arbitrarios."),

            Guide("hooks-overview", "Hooks de script (onStart, onUpdate, …)",
                "Los hooks son funciones globales del chunk que el runtime invoca por nombre en momentos concretos.",
                "En FUEngine: onStart al activar el objeto; onUpdate(dt) cada frame; onDestroy al destruir. Los nombres exactos y eventos extra (colisión, etc.) dependen del proyecto y KnownEvents.",
                "Scripts de capa usan onLayerUpdate(dt) y la tabla layer en lugar de self.",
                "Si un hook no existe, simplemente no se llama; si existe pero lanza error, puede detener el script hasta hot reload.",
                "Para detalle de firmas y eventos: manual «Eventos y hooks Lua» y LuaSpotlightDescriptions en el código."),

            Guide("self-world-overview", "self vs world — tablas de instancia y de escena",
                "self es el proxy del objeto que posee el script; world representa el mapa, búsqueda de objetos, tiles y a veces física de escena.",
                "En FUEngine: self.x, self.y, self:setPosition son el transform; world.findObject, world.setTile, world.raycast son consultas globales.",
                "No mezcles responsabilidades: mover «al otro» suele ser world.setPosition o proxies; no asumas APIs que no estén en la referencia.",
                "Multiselección: el inspector puede no mostrar variables @prop; scripts siguen siendo por objeto.",
                "Para APIs detalladas abre el tema del manual «Scripting Lua — referencia completa de APIs»."),

            Guide("ui-bind-callbacks", "ui.bind y callbacks de UI",
                "ui.bind asocia un canvas o control a funciones que el motor llama cuando cambia el estado o el usuario interactúa.",
                "En FUEngine: los callbacks de UI deben ser ligeros; trabajo pesado en onUpdate o en sistemas de juego.",
                "Usa return temprano si el canvas no aplica a un objeto o estado.",
                "Combina con pcall si el contenido del callback puede fallar (datos de usuario, texto).",
                "Manual general: tema «GUI (Canvas) y Lua en Play»; ejemplos: ids `script-ex-ui-boton-hud-pausar-movimiento`, `script-ex-escenas-tecla-o-boton-loadscene` (pestaña Ejemplos).",
                "Detalle de controles y referencia de APIs ui.*: manual «Scripting Lua — referencia completa de APIs» y tema «Iluminación, audio y UI»."),

            Guide("layer-scripts", "Scripts de capa (layer) vs objeto",
                "Un script asignado a una capa del mapa recibe la tabla layer y no tiene self de objeto.",
                "En FUEngine: onLayerUpdate(dt) en lugar de onUpdate; útil para oleadas, animación de tilemap o lógica global de capa.",
                "No intentes acceder a self.x desde un script de capa salvo que el motor exponga un contexto distinto.",
                "Registrar el script en la capa y en scripts.json sigue el flujo del proyecto.",
                "Ver manual «Scripts de capa (layer)»."),

            Guide("performance-lua", "Rendimiento: tablas, basura y bucles",
                "Cada tabla nueva en Lua consume allocaciones; en bucles ajustados reutiliza tablas o caches local.",
                "En FUEngine: onUpdate se ejecuta muchas veces por segundo; evita pairs sobre miles de entradas sin necesidad.",
                "Prefiere tipos numéricos contiguos y arrays 1..n cuando el algoritmo lo permita.",
                "Precalcula constantes en onStart en lugar de repetir literales complejos.",
                "Perfila con os.clock solo en desarrollo; en release mide FPS y tiempo de frame en hardware objetivo."),

            Guide("bitwise-operators", "Operadores bitwise (Lua 5.3+)",
                "En Lua 5.3+ existen operadores &, |, ~, <<, >> y ~ unario para enteros; en versiones anteriores se usa bit32 o librería externa.",
                "En FUEngine: comprueba la versión de Lua embebida antes de usar sintaxis & |; si no está disponible, usa bit32 (si está) o lógica aritmética.",
                "Útiles para máscaras de flags, tile IDs y protocolos compactos.",
                "No mezcles floats y bitwise sin convertir con math.floor.",
                "Si el compilador rechaza el operador, el script no carga: revisa la consola al iniciar Play."),

            Guide("estructura-carpetas-proyecto", "Carpetas del proyecto y dónde van los scripts",
                "Un proyecto FUEngine es una carpeta en disco con archivos JSON, assets y scripts; no es un «proyecto solución» aparte.",
                "En FUEngine: lo habitual es `Scripts/` para .lua, `scripts.json` en la raíz del proyecto listando cada script (id + ruta relativa), `Maps`/`Objects`/`Escenas` según escenas, `Assets/` (texturas, sonidos, …) y `Autoguardados/` para copias de seguridad del editor — no para que Lua escriba ahí en Play.",
                "Puedes crear subcarpetas dentro de `Scripts/` (p. ej. `Scripts/Enemies/`, `Scripts/UI/`) y poner .lua ahí; la ruta en scripts.json debe ser relativa al proyecto con barras `/` o `\\` coherentes.",
                "El explorador del editor muestra el árbol de carpetas: crear carpeta y archivo .lua desde ahí o desde el Explorador de Windows dentro de la carpeta del proyecto.",
                "Mantén nombres sin caracteres raros para rutas; el motor normaliza rutas relativas al cargar."),

            Guide("scripts-json-registro", "scripts.json: registrar scripts y enlazarlos",
                "`scripts.json` es el registro oficial: cada entrada tiene id estable, nombre y path relativo al .lua dentro del proyecto.",
                "En FUEngine: si el .lua no está en scripts.json, el motor no lo trata como script de juego registrado; la pestaña Scripts del editor ayuda a ver la lista y el registro.",
                "Al crear un .lua nuevo, hay que añadirlo al JSON (o usar el flujo del editor que escribe en scripts.json) para que tenga id y pueda asignarse en el Inspector a objetos o capas.",
                "Arrastrar un .lua al panel de scripts solo funciona si ya existe entrada en scripts.json (validación del editor).",
                "El path en JSON debe coincidir con el archivo real; si mueves o renombras el .lua, actualiza scripts.json o romperás la carga en Play."),

            Guide("crear-script-paso-a-paso", "Crear carpeta, archivo .lua y usarlo en un objeto",
                "Flujo mínimo: (1) En la carpeta del proyecto, crea si quieres una subcarpeta bajo `Scripts/`. (2) Crea un archivo `milogica.lua` (UTF-8). (3) Regístralo en `scripts.json` con ruta relativa correcta. (4) En el Inspector del objeto, añade ese script a la lista y guarda la escena.",
                "En FUEngine: puedes usar el explorador de proyecto del editor para crear carpetas/archivos según la implementación actual; o crear archivos fuera y recargar / registrar.",
                "Escribe hooks globales en el .lua: `function onStart() … end`, `function onUpdate(dt) … end` como espera el runtime para ese contexto.",
                "Pulsa Play: errores de sintaxis y Lua aparecen en la consola del editor en la categoría Lua.",
                "Para varias entidades, usa el mismo .lua en varios objetos (comparten código) o un .lua por tipo; los datos por instancia van en @prop o self según el manual."),

            Guide("datos-temporales-y-disco", "Datos temporales, memoria y ficheros en Play",
                "Durante una partida, el estado temporal vive en variables Lua (local/onUpdate) y en datos del motor; no hace falta un fichero por frame.",
                "En FUEngine (Play) el sandbox no expone io ni acceso libre a rutas del sistema: no puedes abrir, crear ni borrar ficheros arbitrarios como en un script de escritorio. require solo importa módulos .lua bajo Scripts/ (ver guía require).",
                "Para depuración usa print (consola del editor en Play).",
                "La carpeta Autoguardados/ y los JSON del proyecto los gestiona el editor al guardar; no es el guardado de partida del jugador.",
                "Si necesitas persistencia de partida, usa APIs de juego o proyecto documentadas en el manual general cuando existan; no rutas mágicas fuera del proyecto."),
        };
    }

    private static DocumentationTopic Kw(string word, string paraQue, string p1, string p2, string enMotor) =>
        new(
            id: $"lua-kw-{word}",
            title: $"«{word}» — palabra reservada Lua",
            paraQue: paraQue,
            porQueImporta: "Forma parte del lenguaje; el resaltado del editor y Spotlight la reconocen como palabra clave.",
            paragraphs: new[] { p1, p2 },
            bullets: null,
            subtitle: "Palabra reservada Lua · runtime NLua (FUEngine)",
            enMotor: enMotor);

    private static DocumentationTopic Guide(string slug, string title, string paraQue, string enMotor, params string[] paragraphs)
    {
        var body = paragraphs.Where(s => !string.IsNullOrWhiteSpace(s)).Take(6).ToArray();
        return new(
            id: $"lua-guide-{slug}",
            title: title,
            paraQue: paraQue,
            porQueImporta: "Patrones habituales junto a las tablas world, self, input y time del runtime FUEngine.",
            paragraphs: body.Length > 0 ? body : new[] { enMotor },
            bullets: null,
            subtitle: "Guía Lua · sintaxis, librería o uso en el motor",
            enMotor: enMotor);
    }
}
