namespace FUEngine.Spotlight;

/// <summary>
/// Diccionario Spotlight: biblioteca Lua, sintaxis y APIs de motor se indexan aparte (reflexión, hooks).
/// El runtime de juego (<see cref="FUEngine.Runtime.LuaEnvironment"/>) solo expone un subconjunto de globales Lua
/// (string, table, math, pairs, ipairs, … y print); muchas entradas de biblioteca aquí son referencia para el editor
/// y pueden no existir en el sandbox del juego.
/// </summary>
internal static class LuaSpotlightBuiltins
{
    internal const string BuiltinSubtitle = "Lua estándar 5.x";

    public static readonly (string Name, string Detail)[] Entries =
    {
        ("print", "Imprime argumentos en la consola del editor (salida Lua)."),
        ("assert", "Lanza error si la condición es falsa."),
        ("error", "Lanza un error con mensaje."),
        ("pcall", "Llama a una función protegida; devuelve éxito y resultado o error."),
        ("xpcall", "Como pcall con manejador de error."),
        ("load", "Carga un chunk de Lua desde string o función."),
        ("loadfile", "Carga un chunk desde archivo."),
        ("loadstring", "Alias típico de load con string (Lua 5.1)."),
        ("pairs", "Iterador sobre tabla (claves no ordenadas)."),
        ("ipairs", "Iterador sobre array (índices 1..n)."),
        ("next", "Siguiente par clave-valor en una tabla."),
        ("tonumber", "Convierte a número."),
        ("tostring", "Convierte a cadena."),
        ("type", "Tipo del valor: string, number, table, etc."),
        ("select", "Selecciona argumentos ... después del índice."),
        ("unpack", "Desempaqueta una tabla en valores (table.unpack en 5.2+)."),
        ("rawget", "Obtiene sin metamétodos."),
        ("rawset", "Asigna sin metamétodos."),
        ("rawequal", "Igualdad sin metamétodos."),
        ("rawlen", "Longitud sin metamétodos."),
        ("setmetatable", "Asigna metatabla."),
        ("getmetatable", "Obtiene metatabla."),
        ("collectgarbage", "Control del recolector de basura."),
        ("dofile", "Ejecuta un archivo Lua."),
        ("require", "Carga módulo (si el host lo permite)."),
        ("string.format", "Formatea como printf."),
        ("string.len", "Longitud de cadena."),
        ("string.sub", "Subcadena."),
        ("string.find", "Busca patrón en cadena."),
        ("string.gsub", "Sustituye en cadena."),
        ("string.match", "Coincidencia de patrón."),
        ("string.gmatch", "Iterador de coincidencias."),
        ("string.lower", "A minúsculas."),
        ("string.upper", "A mayúsculas."),
        ("string.rep", "Repite cadena."),
        ("string.reverse", "Invierte cadena."),
        ("table.insert", "Inserta en tabla array."),
        ("table.remove", "Elimina de tabla array."),
        ("table.concat", "Concatena valores de array."),
        ("table.sort", "Ordena array in-place."),
        ("table.pack", "Empaqueta ... en tabla."),
        ("table.unpack", "Desempaqueta tabla en valores."),
        ("math.abs", "Valor absoluto."),
        ("math.floor", "Entero por defecto hacia abajo."),
        ("math.ceil", "Entero hacia arriba."),
        ("math.min", "Mínimo de números."),
        ("math.max", "Máximo de números."),
        ("math.random", "Aleatorio (semilla con randomseed)."),
        ("math.randomseed", "Semilla para random."),
        ("math.sqrt", "Raíz cuadrada."),
        ("math.sin", "Seno (radianes)."),
        ("math.cos", "Coseno (radianes)."),
        ("math.rad", "Grados a radianes."),
        ("math.deg", "Radianes a grados."),
        ("math.pi", "Constante π."),
        ("math.huge", "Infinito positivo."),
        ("os.clock", "Tiempo de CPU aproximado."),
        ("os.time", "Marca de tiempo."),
        ("os.date", "Fecha formateada."),
        ("os.difftime", "Diferencia de tiempos."),
        ("os.getenv", "Variable de entorno (puede estar deshabilitado en sandbox)."),
        ("os.execute", "Ejecuta comando del sistema (suele estar deshabilitado en sandbox)."),
        ("os.exit", "Termina el proceso (normalmente no disponible en entornos embebidos)."),
        ("os.remove", "Borra archivo (si el host permite E/S)."),
        ("os.rename", "Renombra archivo (si el host permite E/S)."),
        ("os.tmpname", "Nombre temporal de archivo (poco habitual en juegos)."),

        ("math.tan", "Tangente (radianes)."),
        ("math.asin", "Arcoseno."),
        ("math.acos", "Arcocoseno."),
        ("math.atan", "Arcotangente (un argumento)."),
        ("math.atan2", "Arcotangente de y/x (dos argumentos)."),
        ("math.exp", "e^x."),
        ("math.log", "Logaritmo natural; en Lua 5.2+ acepta base opcional."),
        ("math.log10", "Logaritmo base 10 (Lua 5.1; en 5.2+ usar log con base)."),
        ("math.pow", "Potencia x^y."),
        ("math.modf", "Parte entera y fraccionaria."),
        ("math.fmod", "Resto de división en coma flotante."),
        ("math.cosh", "Coseno hiperbólico."),
        ("math.sinh", "Seno hiperbólico."),
        ("math.tanh", "Tangente hiperbólica."),

        ("string.byte", "Código(s) numérico(s) de carácter(es)."),
        ("string.char", "Construye cadena desde códigos."),
        ("string.dump", "Serializa función binaria (limitado según host)."),

        ("coroutine.create", "Crea una corrutina a partir de una función."),
        ("coroutine.resume", "Reanuda o inicia la corrutina; devuelve valores."),
        ("coroutine.yield", "Suspende la corrutina y devuelve valores al resume."),
        ("coroutine.status", "Estado: running, suspended, normal, dead."),
        ("coroutine.running", "La corrutina en ejecución o nil."),
        ("coroutine.wrap", "Envuelve función en corrutina llamable como función."),
        ("coroutine.isyieldable", "Indica si se puede yield (Lua 5.3+)."),

        ("debug.debug", "Entra al depurador interactivo (si está disponible)."),
        ("debug.traceback", "Cadena de traza de la pila; útil para errores."),
        ("debug.getinfo", "Metadatos de función/nivel de pila (función, línea, nombre…)."),
        ("debug.getlocal", "Obtiene variable local en nivel de pila."),
        ("debug.setlocal", "Asigna variable local en nivel de pila."),
        ("debug.getupvalue", "Obtiene upvalue cerrada de una función."),
        ("debug.setupvalue", "Asigna upvalue cerrada de una función."),
        ("debug.upvalueid", "Identificador estable de upvalue (Lua 5.2+)."),
        ("debug.upvaluejoin", "Une upvalues entre dos closures (Lua 5.2+)."),
        ("debug.sethook", "Registra hook de depuración (línea, call, return…)."),
        ("debug.gethook", "Obtiene hook y máscara actuales."),
        ("debug.getmetatable", "Metatabla de un valor (vía debug)."),
        ("debug.setmetatable", "Asigna metatabla (vía debug)."),
        ("debug.getregistry", "Tabla del registro C/Lua."),
        ("debug.getuservalue", "User value asociado a userdata (Lua 5.2+)."),
        ("debug.setuservalue", "Asigna user value (Lua 5.2+)."),

        ("bit32.arshift", "Desplazamiento aritmético a la derecha."),
        ("bit32.band", "AND bit a bit."),
        ("bit32.bnot", "NOT bit a bit."),
        ("bit32.bor", "OR bit a bit."),
        ("bit32.bxor", "XOR bit a bit."),
        ("bit32.btest", "Comprueba si el AND de máscaras es distinto de cero."),
        ("bit32.extract", "Extrae campo de bits de un entero."),
        ("bit32.replace", "Sustituye campo de bits en un entero."),
        ("bit32.lrotate", "Rotación a la izquierda."),
        ("bit32.rrotate", "Rotación a la derecha."),
        ("bit32.lshift", "Desplazamiento lógico a la izquierda."),
        ("bit32.rshift", "Desplazamiento lógico a la derecha."),
        ("bit32.countlz", "Cuenta ceros a la izquierda (leading zeros)."),
        ("bit32.countrz", "Cuenta ceros a la derecha (trailing zeros)."),

        ("utf8.char", "Cadena UTF-8 desde puntos de código (Lua 5.3+)."),
        ("utf8.codes", "Iterador sobre secuencias UTF-8 en una cadena."),
        ("utf8.codepoint", "Punto(s) de código UTF-8 desde posición."),
        ("utf8.len", "Longitud en caracteres UTF-8 (no en bytes)."),
        ("utf8.offset", "Offset de byte para carácter UTF-8."),

        ("io.close", "Cierra archivo."),
        ("io.flush", "Vuelca buffers de salida."),
        ("io.input", "Obtiene o fija stream de entrada estándar."),
        ("io.lines", "Iterador de líneas desde archivo o stdin."),
        ("io.open", "Abre archivo (lectura/escritura; puede estar restringido)."),
        ("io.output", "Obtiene o fija stream de salida estándar."),
        ("io.popen", "Abre proceso con tubería (suele estar deshabilitado)."),
        ("io.read", "Lee desde stdin o stream actual."),
        ("io.tmpfile", "Archivo temporal."),
        ("io.type", "Tipo de handle de archivo."),
        ("io.write", "Escribe en stdout o stream actual."),
        ("io.stdin", "Entrada estándar."),
        ("io.stdout", "Salida estándar."),
        ("io.stderr", "Salida de errores."),

        ("file:close", "Cierra un archivo abierto con io.open."),
        ("file:flush", "Vuelca el buffer de escritura."),
        ("file:lines", "Iterador de líneas del archivo."),
        ("file:read", "Lee datos según formato o tamaño."),
        ("file:seek", "Posición de lectura/escritura."),
        ("file:setvbuf", "Modo de buffer (full/line/none)."),
        ("file:write", "Escribe valores al archivo."),

        ("package.config", "Separadores y rutas del cargador de módulos."),
        ("package.cpath", "Ruta de búsqueda de módulos C."),
        ("package.loaded", "Tabla de módulos ya cargados."),
        ("package.loaders", "Lista de buscadores de módulos (Lua 5.1)."),
        ("package.loadlib", "Carga biblioteca dinámica (C)."),
        ("package.path", "Ruta de búsqueda de módulos Lua."),
        ("package.preload", "Tabla de cargadores preload."),
        ("package.searchers", "Buscadores de módulos (Lua 5.2+)."),
        ("package.searchpath", "Resuelve nombre de módulo a ruta."),
        ("module", "Estilo de módulo antiguo (Lua 5.1; deprecado en versiones nuevas)."),
        ("package.seeall", "Hace visibles globales al módulo (Lua 5.1; usar con precaución)."),
    };
}
